// <auto-generated />
using System;
using Alpixa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alpixa.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AlpixaDbContext))]
    [Migration("20260929214129_TemplateAssets")]
    partial class TemplateAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Alpixa.Core.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Alpixa.Core.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HealthOverrideAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Parallelism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PauseReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackOpens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Alpixa.Core.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsentSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftBounceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("EmailNormalized");

                    b.HasIndex("ListId", "EmailNormalized")
                        .IsUnique();

                    b.HasIndex("ListId", "Status");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Alpixa.Core.Models.ContactList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsentConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsentConfirmedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactLists");
                });

            modelBuilder.Entity("Alpixa.Core.Models.DeliveryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized");

                    b.HasIndex("CampaignId", "Kind");

                    b.ToTable("DeliveryEvents");
                });

            modelBuilder.Entity("Alpixa.Core.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Alpixa.Core.Models.SendJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmtpCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("MessageId");

                    b.HasIndex("SentUtc");

                    b.HasIndex("CampaignId", "ContactId")
                        .IsUnique();

                    b.HasIndex("CampaignId", "Status", "Sequence");

                    b.ToTable("SendJobs");
                });

            modelBuilder.Entity("Alpixa.Core.Models.SenderProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Auth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DkimDomain")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DkimEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DkimPrivateKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DkimSelector")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImapEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImapHost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImapLastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ImapLastUid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImapPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImapSecurity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImapUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerMinuteLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Security")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WarmupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WarmupStartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SenderProfiles");
                });

            modelBuilder.Entity("Alpixa.Core.Models.SuppressionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("Suppressions");
                });

            modelBuilder.Entity("Alpixa.Core.Models.TemplateAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateAttachments");
                });

            modelBuilder.Entity("Alpixa.Core.Models.Contact", b =>
                {
                    b.HasOne("Alpixa.Core.Models.ContactList", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alpixa.Core.Models.TemplateAttachment", b =>
                {
                    b.HasOne("Alpixa.Core.Models.EmailTemplate", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alpixa.Core.Models.ContactList", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Alpixa.Core.Models.EmailTemplate", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
