<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Alpixa.Sending</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alpixa.Core\Alpixa.Core.csproj" />
    <ProjectReference Include="..\Alpixa.Infrastructure\Alpixa.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly.Core" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Alpixa.Tests" />
  </ItemGroup>

</Project>
